% https://ww2.mathworks.cn/help/vision/examples/motion-based-multiple-object-tracking.html
% main function
% --------------------sub function------
function tracks = initializedTracks()
	tracks =  struct(...
		'id',{},...
		'bbox',{},...
		'kalmanFilter',{},...
		'age',{},...
		'totalVisibleCount',{},...
		'consecutiveInvisibleCount',{});
end


